species: mouse

seq_info:
  type: RNA-Seq
  stranded: yes
  mode: SE
  replicate: 3
  #replicate: 3+4+3+3 (if the number of replicates are different for each sample)

path: /home/xfu/Project/XXX/fastq/

samples:
  - WT_1
  - WT_2
  - WT_3
  - KO_1
  - KO_2
  - KO_3

groups:
  - WT
  - WT
  - WT
  - KO
  - KO
  - KO

design_table: design_table.tsv
#design_table: none

venn_table: venn_table.tsv

group_vs: 
  - 1 4

group_info:
  WT: wild-type
  KO: knock-out

cpu: 30

strandness_hisat2: R ## R (SE); RF (PE)

strandness_htseq: reverse

conda_path: /home/xfu/miniconda2/envs/gmatic/bin

Rscript_path: /home/xfu/R/3.2.4/bin/Rscript

rseqc_path: /home/xfu/Python/rseqc/bin

adapter: /home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa


index: /home/xfu/Gmatic6/genome/mm10/mm10

gtf: /home/xfu/Gmatic6/gene/mm10_vM13/gencode_mm10_vM13.gtf

bed: /home/xfu/Gmatic6/gene/mm10_vM13/gencode_mm10_vM13.bed

gene_anno: /home/xfu/Gmatic6/gene/mm10_vM13/gencode_mm10_vM13_gene_type_name

gene_length: ./script/mm10_merged_exons_length.tsv

AS: /home/xfu/Gmatic6/gene/mm10_vM13/ASTA/gencode_astalavista.bed

AS_RI:  /home/xfu/Gmatic6/gene/mm10_vM13/ASTA/gencode_astalavista_RI.bed

IGV: /home/xfu/igv/genomes/mm10.genome

AStype:
  - SE
  - RI
  - A3SS
  - A5SS
  - AFE
  - ALE
  - MXE

fold_change: 
  - 1.5
  - 2
